### ISSUE TITLE
nil values appear blank in iRuby notebooks

### ISSUE THREAD

**Issue by lokeshh** [SciRuby/sciruby-notebooks#13]
I think it would be better if nils values are printed as `nil` rather than blank in the notebook. It's also good for consistency since in the ruby console the values appear as `nil` rather than as blank.

Here's an example showing how nil values appear when printing data frame with nils in iRuby notebook:

![image](http://i.imgur.com/rudZ7rO.png)

**Comment by v0dro** [comment]
Thats because `NilClass#to_s` produces no output.

**Comment by v0dro** [comment]
Also this is an iruby issue and belongs in the iRuby issue tracker. Closing.
