### ISSUE TITLE
Best fit line example in notebook

### ISSUE THREAD

**Issue by Arafatk** [SciRuby/sciruby-notebooks#15]
In the notebook [here](http://nbviewer.jupyter.org/github/SciRuby/sciruby-notebooks/blob/master/Visualization/Visualizing%20data%20with%20daru%20DataFrame.ipynb) in the last  example, the line of best fit is computed using 
```
sum_x  = df[:fat].sum
sum2_x = df[:fat].sum_of_squares
sum_x  = df[:calories].sum
sum_xy = (df[:fat]*df[:calories]).sum
mean_x = df[:fat].mean
mean_y = df[:calories].mean
slope = (sum_xy - sum_x * mean_y) / (sum2_x - sum_x * mean_x)
yint  = mean_y - slope * mean_x
```

But I think the correct code is 
```
sum_x  = df[:fat].sum
sum2_x = (df[:fat]*df[:fat]).sum 
sum_y  = df[:calories].sum
sum_xy = (df[:fat]*df[:calories]).sum
mean_x = df[:fat].mean
mean_y = df[:calories].mean
slope = (sum_xy - sum_x * mean_y) / (sum2_x - sum_x * mean_x)
yint  = mean_y - slope * mean_x
```
Basically the `df[:fat].sum_of_squares` is actually the sum of squared error(so that must be changed to  `df[:fat]*df[:fat]).sum `), and `sum_x  = df[:calories].sum ` must be changed to` sum_y  = df[:calories].sum`. The formula can be seen [here](http://mathworld.wolfram.com/LeastSquaresFitting.html)  in equation 14(divide numerator and denominator by n). 

The results can be verified using numpy or using the original webpage for the [example](http://mathbits.com/MathBits/TISection/Statistics1/LineFit.htm)
```
import numpy as np
x = np.array([9,13 ,21 ,30 ,31 ,31 ,34 ,25 ,28 ,20 ,5])
y = np.array([260,320,420,530,560,550,590,500,560,440,300])
A = np.vstack([x, np.ones(len(x))]).T
m, c = np.linalg.lstsq(A, y)[0]
print "slope ", m," y- Intercept ", c
```
The correct slope is 11.73 and intercept is 193.85. 
If this is okay, I can send a pr.

**Comment by Arafatk** [comment]
@v0dro please take a look.

**Comment by v0dro** [comment]
I'm occupied with college submissions. Will confirm by tomorrow.

**Comment by v0dro** [comment]
Been occupied with college submissions. 

I just had a look. You're right, `sum_of_squares` should not be used there. And I think `sum_y` wont get used anywhere so can remove that line.
