### ISSUE TITLE
update dockerfile dependencies

### ISSUE THREAD

**Issue by minad** [SciRuby/sciruby-notebooks#2]
@v0dro the docker dependencies (see Dockerfile) need to be updated to work with you notebooks at some point. You don't have to do this now, especially if you are not familiar with docker.

**Comment by v0dro** [comment]
I'll get familiar with docker once new versions of statsample and daru are released. Will update accordingly then.

**Comment by minad** [comment]
Ok, cool. If you have any questions feel free to ask. But in general it is very simple. An image for this repository is automatically generated at https://registry.hub.docker.com/u/minad/sciruby-notebooks

**Comment by minad** [comment]
@v0dro the list of gems has to be updated in https://github.com/sciruby/sciruby

**Comment by v0dro** [comment]
Wow that looks useful!

**Comment by minad** [comment]
the problem is - there is a lot of legacy code lying around, e.g. plotrb/...

for now I included nearly all of them into the sciruby gem, but we should update the list of useful gems from time to time
