### ISSUE TITLE
Docker build fails due to Gem::DependencyResolutionError

### ISSUE THREAD

**Issue by dmmmdfll** [SciRuby/sciruby-notebooks#9]
I tried the following command after cloning and entering the repo:

`docker build .`

Error as follows:

> Step 4 : RUN gem install --no-rdoc --no-ri sciruby-full && iruby register
>  ---> Running in cf54aa3c49d1
> ^[[91mERROR:  While executing gem ... (Gem::DependencyResolutionError)
>     conflicting dependencies nmatrix (= 0.2.0) and nmatrix (~> 0.1)
>   Activated nmatrix-0.1.0 via:
>     nmatrix-0.1.0 (~> 0.1), sciruby-full-0.2.8 (= 0.2.8)
>   instead of (= 0.2.0) via:
>     nmatrix-lapacke-0.2.0 (~> 0.2.0), mixed_models-0.1.1 (~> 0.1), sciruby-full-0. 2.8 (= 0.2.8)
> ^[[0mThe command '/bin/sh -c gem install --no-rdoc --no-ri sciruby-full && iruby   register' returned a non-zero code: 1

I'm on a Linux machine.

> Linux DX4860 3.16.0-51-generic #69~14.04.1-Ubuntu SMP Wed Oct 7 15:32:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I'm new enough Docker and Ruby to not know where to begin to troubleshoot this. Thanks.

**Comment by minad** [comment]
should be fixed
